---
schema:
  procedures: {}
  tables:
    image_download_history:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - vm_image_url
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        download_time:
          data_type: integer
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: download_time
          order: 3
          size:
            - 0
        vm_image_file:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: vm_image_file
          order: 2
          size:
            - 0
        vm_image_url:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: vm_image_url
          order: 1
          size:
            - 0
      indices: []
      name: image_download_history
      options: []
      order: 1
    job_history:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        args:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: args
          order: 4
          size:
            - 0
        creation_time:
          data_type: integer
          default_value: 0
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: creation_time
          order: 6
          size:
            - 0
        end_time:
          data_type: integer
          default_value: 0
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: end_time
          order: 8
          size:
            - 0
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        last_modified:
          data_type: integer
          default_value: 0
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: last_modified
          order: 9
          size:
            - 0
        masterinfo:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: masterinfo
          order: 11
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 2
          size:
            - 0
        result:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: result
          order: 5
          size:
            - 0
        start_time:
          data_type: integer
          default_value: 0
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: start_time
          order: 7
          size:
            - 0
        state:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: state
          order: 3
          size:
            - 0
        workerinfo:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: workerinfo
          order: 10
          size:
            - 0
      indices: []
      name: job_history
      options: []
      order: 2
    job_history_sub:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 0
          expression: ''
          fields:
            - job_id
          match_type: ''
          name: job_history_sub_fk_job_id
          on_delete: CASCADE
          on_update: NO ACTION
          options: []
          reference_fields:
            - id
          reference_table: job_history
          type: FOREIGN KEY
      fields:
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        job_id:
          data_type: integer
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: job_id
          order: 2
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 3
          size:
            - 0
        result:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: result
          order: 5
          size:
            - 0
        state:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: state
          order: 4
          size:
            - 0
      indices:
        - fields:
            - job_id
          name: job_history_sub_idx_job_id
          options: []
          type: NORMAL
      name: job_history_sub
      options: []
      order: 7
    obs_check_history:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - api_url
            - project
            - package
          match_type: ''
          name: api_url_project_package_unique
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        api_url:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 1
          name: api_url
          order: 2
          size:
            - 0
        check_time:
          data_type: integer
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: check_time
          order: 6
          size:
            - 0
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        package:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 1
          name: package
          order: 4
          size:
            - 0
        project:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 1
          name: project
          order: 3
          size:
            - 0
        vm_image_url:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: vm_image_url
          order: 5
          size:
            - 0
      indices: []
      name: obs_check_history
      options: []
      order: 3
    role:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        role:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: role
          order: 2
          size:
            - 32
      indices: []
      name: role
      options: []
      order: 4
    user:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        deleted:
          data_type: boolean
          default_value: 0
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: deleted
          order: 6
          size:
            - 0
        email:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: email
          order: 5
          size:
            - 255
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        lastlogin:
          data_type: datetime
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: lastlogin
          order: 7
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 4
          size:
            - 128
        password:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: password
          order: 3
          size:
            - 40
        pw_changed:
          data_type: datetime
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: pw_changed
          order: 8
          size:
            - 0
        pw_reset_code:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: pw_reset_code
          order: 9
          size:
            - 255
        username:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: username
          order: 2
          size:
            - 32
      indices: []
      name: user
      options: []
      order: 5
    user_roles:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - user_id
            - role_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 0
          expression: ''
          fields:
            - role_id
          match_type: ''
          name: user_roles_fk_role_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: role
          type: FOREIGN KEY
        - deferrable: 0
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: user_roles_fk_user_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: user
          type: FOREIGN KEY
      fields:
        role_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: role_id
          order: 2
          size:
            - 0
        user_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: user_id
          order: 1
          size:
            - 0
      indices:
        - fields:
            - role_id
          name: user_roles_idx_role_id
          options: []
          type: NORMAL
        - fields:
            - user_id
          name: user_roles_idx_user_id
          options: []
          type: NORMAL
      name: user_roles
      options: []
      order: 9
    ws_session:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - session_token
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        filters:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: filters
          order: 4
          size:
            - 0
        permissions:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: permissions
          order: 3
          size:
            - 0
        session_token:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: session_token
          order: 1
          size:
            - 32
        user_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: user_id
          order: 2
          size:
            - 0
      indices: []
      name: ws_session
      options: []
      order: 6
    wstoken:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - auth_token
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: wstoken_fk_user_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: user
          type: FOREIGN KEY
      fields:
        auth_token:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: auth_token
          order: 2
          size:
            - 32
        user_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: user_id
          order: 1
          size:
            - 0
      indices:
        - fields:
            - user_id
          name: wstoken_idx_user_id
          options: []
          type: NORMAL
      name: wstoken
      options: []
      order: 8
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - ImageDownloadHistory
      - JobHistory
      - JobHistorySub
      - ObsCheckHistory
      - Role
      - User
      - UserRole
      - WsSession
      - WsToken
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11021
